name: image-recognition
channels:
  - defaults
  - conda-forge
dependencies:
  - python
  - imageio
  - imageio[ffmpeg]
  - numpy
  - imageio[pyav]
  - requests
  - beautifulsoup4
  - conda-forge::pillow
  - conda-forge::libxcb
  - conda-forge::pyautogui
  - conda-forge::pynput
  - conda-forge::opencv
  - conda-forge::requests
  - conda-forge::seleniumy
